---

language: python
python:
  - "2.7"

cache:
  directories:
    - $HOME/.cache/pip

env:
  global:
    - ANSIBLE_HOST_KEY_CHECKING=False
    - PIP_DOWNLOAD_CACHE=$HOME/.cache/pip

before_install:
  - sudo apt-get update -qq

install:
  - pip install -U pip
  - pip install ansible==2.7 ansible-lint yamllint flake8 molecule docker pytest python-apt

# command to run tests
script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
