---
- name: "A Wildfly Playbook"
  hosts: "{{ wildfly_ansible_hosts | default('localhost') }}"
  vars:
    wfly_home: "/opt/wildfly/wildfly-16.0.0.Final/"
    pgsql_module_dir: "{{ wfly_home }}//modules/org/postgresql/main"
    jdbc_drive_url: https://repo.maven.apache.org/maven2/org/postgresql/postgresql/9.2-1002-jdbc4/postgresql-9.2-1002-jdbc4.jar
    app_url: http://people.redhat.com/~rpelisse/simple-webapp.war
    app: /tmp/simple-webapp.war
  tasks:
    - name: "Add JCliff Repo"
      yum_repository:
        name: jcliff
        description: JCliff repository
        baseurl: http://people.redhat.com/~rpelisse/jcliff.yum/
        gpgcheck: 0

    - name: "Ensure JCliff is installed"
      yum:
        name: jcliff
        state: present

    - name: "Download a demo app to deplou"
      get_url:
        url: "{{ app_url }}"
        dest: "{{ app }}"

    - name: "Deploy internal templates to remote target"
      copy:
        src: templates/rules/
        dest: /etc/ansible/jcliff/

    - name: "Tuning Wildfly using JCliff"
      jcliff:
        wfly_home: "{{ wfly_home }}"
        subsystems:
          - drivers:
              - driver_name: h2
                driver_xa_datasource_class_name: org.h2.jdbcx.JdbcDataSource
                driver_module_name: com.h2database.h2
          - datasources:
              - name: MyPostgresDS
                jndi_name: 'java:jboss/datasources/MyPostgresDS'
                connection_url: 'jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE'
                driver_name: h2
          - system_props:
              - name: myProp
                value: myValue
              - name: myProp2
                value: myValue2
          - deployments:
              - artifact_id: simple-webapp-v1.war
                name: simple-webapp
                path: "{{ app }}"
      notify: "Restart Wildfly Server"

  handlers:
    - name: "Restart Wildfly Server"
      service:
        name: wfly
        state: restarted
