---
- name: "Add JCliff Repo"
  yum_repository:
    name: jcliff
    description: JCliff repository
    baseurl: http://people.redhat.com/~rpelisse/jcliff.yum/
    gpgcheck: 0

- name: "Ensure JCliff is installed"
  yum:
    name: jcliff
    state: present
