---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/yamllint.yml
platforms:
  - name: centos-systemd
    image: centos/systemd:latest
    privileged: True
    port_bindings:
      - 8080:8080
    published_ports:
      - 0.0.0.0:8080:8080/TCP
    command: "/usr/sbin/init"
provisioner:
  name: ansible
  options:
    extra-vars: wildfly_ansible_hosts=all
  lint:
    name: ansible-lint
    options:
      x:
        - 701
scenario:
  name: default
  test_sequence:
    - dependency
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    # -   idempotence
    - side_effect
    - verify
    - destroy

verifier:
  name: testinfra
  lint:
    name: flake8
